name: Test

on:
  workflow_dispatch:
  push: { tags: [ "*" ], branches: [ "main", "develop" ] }

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: true
      max-parallel: 1
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup CIDoer
        uses: ./
      - name: Test CIDoer
        shell: bash
        run: |
          source "${CIDOER_CORE_FILE:?}"
          do_print_dash_pair 'GITHUB_RUN_NUMBER' "${{ github.run_number }}"
